ms_platform_home:
    path:      /{page}
    defaults:
        _controller: MSPlatformBundle:Advert:index
        page:        1
        requirements: \d*
    
ms_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: MSPlatformBundle:Advert:view }
    requirements: \d+

ms_platform_add:
    path:      /add
    defaults:  { _controller: MSPlatformBundle:Advert:add }

ms_plateform_edit:
    path:      /edit/{id}
    defaults:  { _controller: MSPlatformBundle:Advert:edit }
    requirements:
        id: \d+

ms_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+